/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as FranquiciasRouteImport } from './routes/franquicias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciasRoute = FranquiciasRouteImport.update({
  id: '/franquicias',
  path: '/franquicias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRoute
  '/menu': typeof MenuRoute
  '/sedes': typeof SedesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRoute
  '/menu': typeof MenuRoute
  '/sedes': typeof SedesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRoute
  '/menu': typeof MenuRoute
  '/sedes': typeof SedesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/franquicias'
    | '/historias'
    | '/menu'
    | '/sedes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/franquicias' | '/historias' | '/menu' | '/sedes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/franquicias'
    | '/historias'
    | '/menu'
    | '/sedes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FranquiciasRoute: typeof FranquiciasRoute
  HistoriasRoute: typeof HistoriasRoute
  MenuRoute: typeof MenuRoute
  SedesRoute: typeof SedesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicias': {
      id: '/franquicias'
      path: '/franquicias'
      fullPath: '/franquicias'
      preLoaderRoute: typeof FranquiciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FranquiciasRoute: FranquiciasRoute,
  HistoriasRoute: HistoriasRoute,
  MenuRoute: MenuRoute,
  SedesRoute: SedesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
