/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as NoAutorizadoRouteImport } from './routes/no-autorizado'
import { Route as MiReinoRouteImport } from './routes/mi-reino'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as FranquiciasRouteImport } from './routes/franquicias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiReinoIndexRouteImport } from './routes/mi-reino.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HistoriasSlugRouteImport } from './routes/historias.$slug'

const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAutorizadoRoute = NoAutorizadoRouteImport.update({
  id: '/no-autorizado',
  path: '/no-autorizado',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReinoRoute = MiReinoRouteImport.update({
  id: '/mi-reino',
  path: '/mi-reino',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciasRoute = FranquiciasRouteImport.update({
  id: '/franquicias',
  path: '/franquicias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReinoIndexRoute = MiReinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiReinoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HistoriasSlugRoute = HistoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HistoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-reino': typeof MiReinoRouteWithChildren
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/mi-reino/': typeof MiReinoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/mi-reino': typeof MiReinoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-reino': typeof MiReinoRouteWithChildren
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/mi-reino/': typeof MiReinoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/franquicias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/mi-reino'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/historias/$slug'
    | '/admin/'
    | '/mi-reino/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/franquicias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/historias/$slug'
    | '/admin'
    | '/mi-reino'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/franquicias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/mi-reino'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/historias/$slug'
    | '/admin/'
    | '/mi-reino/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FranquiciasRoute: typeof FranquiciasRoute
  HistoriasRoute: typeof HistoriasRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MiReinoRoute: typeof MiReinoRouteWithChildren
  NoAutorizadoRoute: typeof NoAutorizadoRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SedesRoute: typeof SedesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-autorizado': {
      id: '/no-autorizado'
      path: '/no-autorizado'
      fullPath: '/no-autorizado'
      preLoaderRoute: typeof NoAutorizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reino': {
      id: '/mi-reino'
      path: '/mi-reino'
      fullPath: '/mi-reino'
      preLoaderRoute: typeof MiReinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicias': {
      id: '/franquicias'
      path: '/franquicias'
      fullPath: '/franquicias'
      preLoaderRoute: typeof FranquiciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reino/': {
      id: '/mi-reino/'
      path: '/'
      fullPath: '/mi-reino/'
      preLoaderRoute: typeof MiReinoIndexRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/historias/$slug': {
      id: '/historias/$slug'
      path: '/$slug'
      fullPath: '/historias/$slug'
      preLoaderRoute: typeof HistoriasSlugRouteImport
      parentRoute: typeof HistoriasRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HistoriasRouteChildren {
  HistoriasSlugRoute: typeof HistoriasSlugRoute
}

const HistoriasRouteChildren: HistoriasRouteChildren = {
  HistoriasSlugRoute: HistoriasSlugRoute,
}

const HistoriasRouteWithChildren = HistoriasRoute._addFileChildren(
  HistoriasRouteChildren,
)

interface MiReinoRouteChildren {
  MiReinoIndexRoute: typeof MiReinoIndexRoute
}

const MiReinoRouteChildren: MiReinoRouteChildren = {
  MiReinoIndexRoute: MiReinoIndexRoute,
}

const MiReinoRouteWithChildren =
  MiReinoRoute._addFileChildren(MiReinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FranquiciasRoute: FranquiciasRoute,
  HistoriasRoute: HistoriasRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MiReinoRoute: MiReinoRouteWithChildren,
  NoAutorizadoRoute: NoAutorizadoRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SedesRoute: SedesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
