/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as NoAutorizadoRouteImport } from './routes/no-autorizado'
import { Route as MiReinoRouteImport } from './routes/mi-reino'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as FranquiciasRouteImport } from './routes/franquicias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiReinoIndexRouteImport } from './routes/mi-reino.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MiReinoPuntosRouteImport } from './routes/mi-reino.puntos'
import { Route as MiReinoPedidosRouteImport } from './routes/mi-reino.pedidos'
import { Route as MiReinoFavoritosRouteImport } from './routes/mi-reino.favoritos'
import { Route as MiReinoDatosRouteImport } from './routes/mi-reino.datos'
import { Route as HistoriasSlugRouteImport } from './routes/historias.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSincronizacionRouteImport } from './routes/admin.sincronizacion'
import { Route as AdminSedesRouteImport } from './routes/admin.sedes'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminContenidosRouteImport } from './routes/admin.contenidos'
import { Route as AdminSedesIndexRouteImport } from './routes/admin.sedes.index'
import { Route as AdminContenidosIndexRouteImport } from './routes/admin.contenidos.index'
import { Route as AdminSedesNuevoRouteImport } from './routes/admin.sedes.nuevo'
import { Route as AdminSedesIdRouteImport } from './routes/admin.sedes.$id'
import { Route as AdminContenidosNuevoRouteImport } from './routes/admin.contenidos.nuevo'
import { Route as AdminContenidosIdRouteImport } from './routes/admin.contenidos.$id'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAutorizadoRoute = NoAutorizadoRouteImport.update({
  id: '/no-autorizado',
  path: '/no-autorizado',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReinoRoute = MiReinoRouteImport.update({
  id: '/mi-reino',
  path: '/mi-reino',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciasRoute = FranquiciasRouteImport.update({
  id: '/franquicias',
  path: '/franquicias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiReinoIndexRoute = MiReinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiReinoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MiReinoPuntosRoute = MiReinoPuntosRouteImport.update({
  id: '/puntos',
  path: '/puntos',
  getParentRoute: () => MiReinoRoute,
} as any)
const MiReinoPedidosRoute = MiReinoPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MiReinoRoute,
} as any)
const MiReinoFavoritosRoute = MiReinoFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => MiReinoRoute,
} as any)
const MiReinoDatosRoute = MiReinoDatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => MiReinoRoute,
} as any)
const HistoriasSlugRoute = HistoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HistoriasRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSincronizacionRoute = AdminSincronizacionRouteImport.update({
  id: '/sincronizacion',
  path: '/sincronizacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSedesRoute = AdminSedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContenidosRoute = AdminContenidosRouteImport.update({
  id: '/contenidos',
  path: '/contenidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSedesIndexRoute = AdminSedesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSedesRoute,
} as any)
const AdminContenidosIndexRoute = AdminContenidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContenidosRoute,
} as any)
const AdminSedesNuevoRoute = AdminSedesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AdminSedesRoute,
} as any)
const AdminSedesIdRoute = AdminSedesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSedesRoute,
} as any)
const AdminContenidosNuevoRoute = AdminContenidosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AdminContenidosRoute,
} as any)
const AdminContenidosIdRoute = AdminContenidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContenidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/gracias': typeof GraciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-reino': typeof MiReinoRouteWithChildren
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/admin/contenidos': typeof AdminContenidosRouteWithChildren
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/sedes': typeof AdminSedesRouteWithChildren
  '/admin/sincronizacion': typeof AdminSincronizacionRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/mi-reino/datos': typeof MiReinoDatosRoute
  '/mi-reino/favoritos': typeof MiReinoFavoritosRoute
  '/mi-reino/pedidos': typeof MiReinoPedidosRoute
  '/mi-reino/puntos': typeof MiReinoPuntosRoute
  '/admin/': typeof AdminIndexRoute
  '/mi-reino/': typeof MiReinoIndexRoute
  '/admin/contenidos/$id': typeof AdminContenidosIdRoute
  '/admin/contenidos/nuevo': typeof AdminContenidosNuevoRoute
  '/admin/sedes/$id': typeof AdminSedesIdRoute
  '/admin/sedes/nuevo': typeof AdminSedesNuevoRoute
  '/admin/contenidos/': typeof AdminContenidosIndexRoute
  '/admin/sedes/': typeof AdminSedesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/gracias': typeof GraciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/sincronizacion': typeof AdminSincronizacionRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/mi-reino/datos': typeof MiReinoDatosRoute
  '/mi-reino/favoritos': typeof MiReinoFavoritosRoute
  '/mi-reino/pedidos': typeof MiReinoPedidosRoute
  '/mi-reino/puntos': typeof MiReinoPuntosRoute
  '/admin': typeof AdminIndexRoute
  '/mi-reino': typeof MiReinoIndexRoute
  '/admin/contenidos/$id': typeof AdminContenidosIdRoute
  '/admin/contenidos/nuevo': typeof AdminContenidosNuevoRoute
  '/admin/sedes/$id': typeof AdminSedesIdRoute
  '/admin/sedes/nuevo': typeof AdminSedesNuevoRoute
  '/admin/contenidos': typeof AdminContenidosIndexRoute
  '/admin/sedes': typeof AdminSedesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/franquicias': typeof FranquiciasRoute
  '/gracias': typeof GraciasRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-reino': typeof MiReinoRouteWithChildren
  '/no-autorizado': typeof NoAutorizadoRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sedes': typeof SedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/admin/contenidos': typeof AdminContenidosRouteWithChildren
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/sedes': typeof AdminSedesRouteWithChildren
  '/admin/sincronizacion': typeof AdminSincronizacionRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/historias/$slug': typeof HistoriasSlugRoute
  '/mi-reino/datos': typeof MiReinoDatosRoute
  '/mi-reino/favoritos': typeof MiReinoFavoritosRoute
  '/mi-reino/pedidos': typeof MiReinoPedidosRoute
  '/mi-reino/puntos': typeof MiReinoPuntosRoute
  '/admin/': typeof AdminIndexRoute
  '/mi-reino/': typeof MiReinoIndexRoute
  '/admin/contenidos/$id': typeof AdminContenidosIdRoute
  '/admin/contenidos/nuevo': typeof AdminContenidosNuevoRoute
  '/admin/sedes/$id': typeof AdminSedesIdRoute
  '/admin/sedes/nuevo': typeof AdminSedesNuevoRoute
  '/admin/contenidos/': typeof AdminContenidosIndexRoute
  '/admin/sedes/': typeof AdminSedesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/franquicias'
    | '/gracias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/mi-reino'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/sitemap.xml'
    | '/tracking'
    | '/admin/contenidos'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/sedes'
    | '/admin/sincronizacion'
    | '/admin/usuarios'
    | '/historias/$slug'
    | '/mi-reino/datos'
    | '/mi-reino/favoritos'
    | '/mi-reino/pedidos'
    | '/mi-reino/puntos'
    | '/admin/'
    | '/mi-reino/'
    | '/admin/contenidos/$id'
    | '/admin/contenidos/nuevo'
    | '/admin/sedes/$id'
    | '/admin/sedes/nuevo'
    | '/admin/contenidos/'
    | '/admin/sedes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/franquicias'
    | '/gracias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/sitemap.xml'
    | '/tracking'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/sincronizacion'
    | '/admin/usuarios'
    | '/historias/$slug'
    | '/mi-reino/datos'
    | '/mi-reino/favoritos'
    | '/mi-reino/pedidos'
    | '/mi-reino/puntos'
    | '/admin'
    | '/mi-reino'
    | '/admin/contenidos/$id'
    | '/admin/contenidos/nuevo'
    | '/admin/sedes/$id'
    | '/admin/sedes/nuevo'
    | '/admin/contenidos'
    | '/admin/sedes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/franquicias'
    | '/gracias'
    | '/historias'
    | '/login'
    | '/menu'
    | '/mi-reino'
    | '/no-autorizado'
    | '/registro'
    | '/reset-password'
    | '/sedes'
    | '/sitemap.xml'
    | '/tracking'
    | '/admin/contenidos'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/sedes'
    | '/admin/sincronizacion'
    | '/admin/usuarios'
    | '/historias/$slug'
    | '/mi-reino/datos'
    | '/mi-reino/favoritos'
    | '/mi-reino/pedidos'
    | '/mi-reino/puntos'
    | '/admin/'
    | '/mi-reino/'
    | '/admin/contenidos/$id'
    | '/admin/contenidos/nuevo'
    | '/admin/sedes/$id'
    | '/admin/sedes/nuevo'
    | '/admin/contenidos/'
    | '/admin/sedes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FranquiciasRoute: typeof FranquiciasRoute
  GraciasRoute: typeof GraciasRoute
  HistoriasRoute: typeof HistoriasRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MiReinoRoute: typeof MiReinoRouteWithChildren
  NoAutorizadoRoute: typeof NoAutorizadoRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SedesRoute: typeof SedesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-autorizado': {
      id: '/no-autorizado'
      path: '/no-autorizado'
      fullPath: '/no-autorizado'
      preLoaderRoute: typeof NoAutorizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reino': {
      id: '/mi-reino'
      path: '/mi-reino'
      fullPath: '/mi-reino'
      preLoaderRoute: typeof MiReinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicias': {
      id: '/franquicias'
      path: '/franquicias'
      fullPath: '/franquicias'
      preLoaderRoute: typeof FranquiciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-reino/': {
      id: '/mi-reino/'
      path: '/'
      fullPath: '/mi-reino/'
      preLoaderRoute: typeof MiReinoIndexRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mi-reino/puntos': {
      id: '/mi-reino/puntos'
      path: '/puntos'
      fullPath: '/mi-reino/puntos'
      preLoaderRoute: typeof MiReinoPuntosRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/mi-reino/pedidos': {
      id: '/mi-reino/pedidos'
      path: '/pedidos'
      fullPath: '/mi-reino/pedidos'
      preLoaderRoute: typeof MiReinoPedidosRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/mi-reino/favoritos': {
      id: '/mi-reino/favoritos'
      path: '/favoritos'
      fullPath: '/mi-reino/favoritos'
      preLoaderRoute: typeof MiReinoFavoritosRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/mi-reino/datos': {
      id: '/mi-reino/datos'
      path: '/datos'
      fullPath: '/mi-reino/datos'
      preLoaderRoute: typeof MiReinoDatosRouteImport
      parentRoute: typeof MiReinoRoute
    }
    '/historias/$slug': {
      id: '/historias/$slug'
      path: '/$slug'
      fullPath: '/historias/$slug'
      preLoaderRoute: typeof HistoriasSlugRouteImport
      parentRoute: typeof HistoriasRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sincronizacion': {
      id: '/admin/sincronizacion'
      path: '/sincronizacion'
      fullPath: '/admin/sincronizacion'
      preLoaderRoute: typeof AdminSincronizacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sedes': {
      id: '/admin/sedes'
      path: '/sedes'
      fullPath: '/admin/sedes'
      preLoaderRoute: typeof AdminSedesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contenidos': {
      id: '/admin/contenidos'
      path: '/contenidos'
      fullPath: '/admin/contenidos'
      preLoaderRoute: typeof AdminContenidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sedes/': {
      id: '/admin/sedes/'
      path: '/'
      fullPath: '/admin/sedes/'
      preLoaderRoute: typeof AdminSedesIndexRouteImport
      parentRoute: typeof AdminSedesRoute
    }
    '/admin/contenidos/': {
      id: '/admin/contenidos/'
      path: '/'
      fullPath: '/admin/contenidos/'
      preLoaderRoute: typeof AdminContenidosIndexRouteImport
      parentRoute: typeof AdminContenidosRoute
    }
    '/admin/sedes/nuevo': {
      id: '/admin/sedes/nuevo'
      path: '/nuevo'
      fullPath: '/admin/sedes/nuevo'
      preLoaderRoute: typeof AdminSedesNuevoRouteImport
      parentRoute: typeof AdminSedesRoute
    }
    '/admin/sedes/$id': {
      id: '/admin/sedes/$id'
      path: '/$id'
      fullPath: '/admin/sedes/$id'
      preLoaderRoute: typeof AdminSedesIdRouteImport
      parentRoute: typeof AdminSedesRoute
    }
    '/admin/contenidos/nuevo': {
      id: '/admin/contenidos/nuevo'
      path: '/nuevo'
      fullPath: '/admin/contenidos/nuevo'
      preLoaderRoute: typeof AdminContenidosNuevoRouteImport
      parentRoute: typeof AdminContenidosRoute
    }
    '/admin/contenidos/$id': {
      id: '/admin/contenidos/$id'
      path: '/$id'
      fullPath: '/admin/contenidos/$id'
      preLoaderRoute: typeof AdminContenidosIdRouteImport
      parentRoute: typeof AdminContenidosRoute
    }
  }
}

interface AdminContenidosRouteChildren {
  AdminContenidosIdRoute: typeof AdminContenidosIdRoute
  AdminContenidosNuevoRoute: typeof AdminContenidosNuevoRoute
  AdminContenidosIndexRoute: typeof AdminContenidosIndexRoute
}

const AdminContenidosRouteChildren: AdminContenidosRouteChildren = {
  AdminContenidosIdRoute: AdminContenidosIdRoute,
  AdminContenidosNuevoRoute: AdminContenidosNuevoRoute,
  AdminContenidosIndexRoute: AdminContenidosIndexRoute,
}

const AdminContenidosRouteWithChildren = AdminContenidosRoute._addFileChildren(
  AdminContenidosRouteChildren,
)

interface AdminSedesRouteChildren {
  AdminSedesIdRoute: typeof AdminSedesIdRoute
  AdminSedesNuevoRoute: typeof AdminSedesNuevoRoute
  AdminSedesIndexRoute: typeof AdminSedesIndexRoute
}

const AdminSedesRouteChildren: AdminSedesRouteChildren = {
  AdminSedesIdRoute: AdminSedesIdRoute,
  AdminSedesNuevoRoute: AdminSedesNuevoRoute,
  AdminSedesIndexRoute: AdminSedesIndexRoute,
}

const AdminSedesRouteWithChildren = AdminSedesRoute._addFileChildren(
  AdminSedesRouteChildren,
)

interface AdminRouteChildren {
  AdminContenidosRoute: typeof AdminContenidosRouteWithChildren
  AdminMenuRoute: typeof AdminMenuRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminSedesRoute: typeof AdminSedesRouteWithChildren
  AdminSincronizacionRoute: typeof AdminSincronizacionRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContenidosRoute: AdminContenidosRouteWithChildren,
  AdminMenuRoute: AdminMenuRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminSedesRoute: AdminSedesRouteWithChildren,
  AdminSincronizacionRoute: AdminSincronizacionRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HistoriasRouteChildren {
  HistoriasSlugRoute: typeof HistoriasSlugRoute
}

const HistoriasRouteChildren: HistoriasRouteChildren = {
  HistoriasSlugRoute: HistoriasSlugRoute,
}

const HistoriasRouteWithChildren = HistoriasRoute._addFileChildren(
  HistoriasRouteChildren,
)

interface MiReinoRouteChildren {
  MiReinoDatosRoute: typeof MiReinoDatosRoute
  MiReinoFavoritosRoute: typeof MiReinoFavoritosRoute
  MiReinoPedidosRoute: typeof MiReinoPedidosRoute
  MiReinoPuntosRoute: typeof MiReinoPuntosRoute
  MiReinoIndexRoute: typeof MiReinoIndexRoute
}

const MiReinoRouteChildren: MiReinoRouteChildren = {
  MiReinoDatosRoute: MiReinoDatosRoute,
  MiReinoFavoritosRoute: MiReinoFavoritosRoute,
  MiReinoPedidosRoute: MiReinoPedidosRoute,
  MiReinoPuntosRoute: MiReinoPuntosRoute,
  MiReinoIndexRoute: MiReinoIndexRoute,
}

const MiReinoRouteWithChildren =
  MiReinoRoute._addFileChildren(MiReinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FranquiciasRoute: FranquiciasRoute,
  GraciasRoute: GraciasRoute,
  HistoriasRoute: HistoriasRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MiReinoRoute: MiReinoRouteWithChildren,
  NoAutorizadoRoute: NoAutorizadoRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SedesRoute: SedesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
